### ISSUE TITLE
fix the issue of installing ghostscript

### ISSUE THREAD

**Issue by royalosyin** [dongli/packman#14]
add the follow lines in the ghostscript.rb. Then it works!

```
    args = %W[
      --prefix=#{prefix}
      --disable-cups
      --disable-compile-inits
      --disable-gtk
      **--with-system-libtiff **
    ]
    
    #PACKMAN.run "sed -i ''s/ZLIBDIR=src/ZLIBDIR=$includedir/' configure.ac configure"
    **PACKMAN.run 'rm -rf freetype lcms2 jpeg libpng'**
    
    PACKMAN.run './configure', *args
```

**Comment by dongli** [comment]
Hi, thanks for open this issue! But it would be great you can describe the problem when installing `ghostscript`.

**Comment by royalosyin** [comment]
In the ghostscript.rb, you already set up the dependencies. So it is not necessary to use these packages of freetype lcms2 jpeg libpng inside the source codes of ghostscript  again.

**Comment by royalosyin** [comment]
To install libgsf, it is necessary to modify the Makefile of bzip2====>
cc=gcc -fPIC.

**Comment by royalosyin** [comment]
There is an error in imagemagick.rb:
modify 'lcms/lcms2.h' => 'lcms2.h', --------->'lcms2/lcms2.h' => 'lcms2.h',

**Comment by dongli** [comment]
I have updated `ghostscript` in commit d71c3eba.
